-- 文创平台菜单初始化

delete from sys_menu where menu_id between 2000 and 2149;

insert into sys_menu values ('2000', '文创平台', '0', '5', 'creative', '', '', '', 1, 0, 'M', '0', '0', '', 'guide', 'admin', sysdate(), '', null, '文创平台目录');
insert into sys_menu values ('2001', '创作者管理', '2000', '1', 'creator', 'creative/creator/index', '', '', 1, 0, 'C', '0', '0', 'creative:creator:list', 'user', 'admin', sysdate(), '', null, '创作者管理菜单');
insert into sys_menu values ('2002', '分类管理', '2000', '2', 'category', 'creative/category/index', '', '', 1, 0, 'C', '0', '0', 'creative:category:list', 'tree', 'admin', sysdate(), '', null, '分类管理菜单');
insert into sys_menu values ('2003', '商品管理', '2000', '3', 'product', 'creative/product/index', '', '', 1, 0, 'C', '0', '0', 'creative:product:list', 'build', 'admin', sysdate(), '', null, '商品管理菜单');
insert into sys_menu values ('2004', '定制需求', '2000', '4', 'demand', 'creative/demand/index', '', '', 1, 0, 'C', '0', '0', 'creative:demand:list', 'form', 'admin', sysdate(), '', null, '定制需求菜单');
insert into sys_menu values ('2005', '定制报价', '2000', '5', 'quote', 'creative/quote/index', '', '', 1, 0, 'C', '0', '0', 'creative:quote:list', 'edit', 'admin', sysdate(), '', null, '定制报价菜单');
insert into sys_menu values ('2006', '定制订单', '2000', '6', 'order', 'creative/order/index', '', '', 1, 0, 'C', '0', '0', 'creative:order:list', 'shopping', 'admin', sysdate(), '', null, '定制订单菜单');
insert into sys_menu values ('2007', '作品分享', '2000', '7', 'post', 'creative/post/index', '', '', 1, 0, 'C', '0', '0', 'creative:post:list', 'message', 'admin', sysdate(), '', null, '作品分享菜单');
insert into sys_menu values ('2008', '评论互动', '2000', '8', 'comment', 'creative/comment/index', '', '', 1, 0, 'C', '0', '0', 'creative:comment:list', 'comment', 'admin', sysdate(), '', null, '评论互动菜单');
insert into sys_menu values ('2009', '收藏关注', '2000', '9', 'favorite', 'creative/favorite/index', '', '', 1, 0, 'C', '0', '0', 'creative:favorite:list', 'peoples', 'admin', sysdate(), '', null, '收藏关注菜单');

insert into sys_menu values ('2100', '创作者查询', '2001', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:creator:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2101', '创作者新增', '2001', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:creator:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2102', '创作者修改', '2001', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:creator:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2103', '创作者删除', '2001', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:creator:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2104', '分类查询', '2002', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:category:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2105', '分类新增', '2002', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:category:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2106', '分类修改', '2002', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:category:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2107', '分类删除', '2002', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:category:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2108', '商品查询', '2003', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:product:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2109', '商品新增', '2003', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:product:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2110', '商品修改', '2003', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:product:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2111', '商品删除', '2003', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:product:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2112', '需求查询', '2004', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:demand:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2113', '需求新增', '2004', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:demand:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2114', '需求修改', '2004', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:demand:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2115', '需求删除', '2004', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:demand:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2116', '报价查询', '2005', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:quote:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2117', '报价新增', '2005', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:quote:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2118', '报价修改', '2005', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:quote:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2119', '报价删除', '2005', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:quote:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2120', '订单查询', '2006', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:order:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2121', '订单新增', '2006', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:order:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2122', '订单修改', '2006', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:order:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2123', '订单删除', '2006', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:order:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2124', '作品查询', '2007', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:post:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2125', '作品新增', '2007', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:post:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2126', '作品修改', '2007', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:post:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2127', '作品删除', '2007', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:post:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2128', '评论查询', '2008', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:comment:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2129', '评论新增', '2008', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:comment:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2130', '评论修改', '2008', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:comment:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2131', '评论删除', '2008', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:comment:remove', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2132', '收藏查询', '2009', '1', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:favorite:query', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2133', '收藏新增', '2009', '2', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:favorite:add', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2134', '收藏修改', '2009', '3', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:favorite:edit', '#', 'admin', sysdate(), '', null, '');
insert into sys_menu values ('2135', '收藏删除', '2009', '4', '', '', '', '', 1, 0, 'F', '0', '0', 'creative:favorite:remove', '#', 'admin', sysdate(), '', null, '');
